version: '3'

services:
  flyway:
    image: flyway/flyway:7.15.0
    command: -url=jdbc:mysql://db -schemas=airportart -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306